kind: pipeline
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
    - git submodule update --init --recursive

- name: build
  image: klakegg/hugo
  commands:
  - cd website
  - hugo

- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts: [ "mindrot.dev" ]
    key:
      from_secret: PRIVATE_KEY
    source: ./website/public
    target: /app/blog