kind: pipeline
name: default

steps:
- name: build
  image: klakegg/hugo
  commands:
  - cd website
  - hugo

- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts: [ "mindrot.dev" ]
    key:
      from_secret: PRIVATE_KEY
    source: ./website/public
    target: /app/blog