languageCode: "en-us"
baseUrl: ""
title: "mindrot/blog"
theme: "anubis"
paginate: 10
enableRobotsTXT: true

params:
  author: "mindrot"
  email: artem.derkach.gs@gmail.com # used for microformats
  description: ""
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light
  readMore: false
  social:
    - id: github
      name: mind-rot

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown